import fs from "node:fs";
fs.mkdirSync("out-scenario", { recursive: true });
import { chromium } from "playwright-core";
const b = await chromium.launch({ channel: "msedge" });
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true });
const p = await ctx.newPage();
const errs = []; p.on("pageerror", (e) => errs.push(e.message)); p.on("console", (m) => { if (m.type() === "error") errs.push(m.text()); });
const shot = (n) => p.screenshot({ path: `out-scenario/t_${n}.png` });
await p.goto("http://localhost:3030/#/start"); await p.evaluate(() => { localStorage.clear(); sessionStorage.clear(); }); await p.reload();
await p.getByRole("button", { name: "Bắt đầu" }).waitFor(); await shot("1_welcome");
await p.getByRole("button", { name: "Bắt đầu" }).click();
await p.getByRole("button", { name: "Năm 2027" }).click(); await p.waitForTimeout(400);
for (const [s, v] of [["Toán","9"],["Hóa học","8.5"],["Sinh học","8"]]) await p.locator(`input[aria-label="Điểm thi – ${s}"]`).fill(v);
await shot("2_exam");
const next = async () => { await p.getByRole("button", { name: /Tiếp tục|Bỏ qua|Xem kết quả/ }).click(); await p.waitForTimeout(250); };
await next();
await p.getByText("Nhập theo từng lớp").click(); await shot("3_hocba_grades");
await next(); await shot("4_cert"); await next(); await shot("5_award");
await p.getByRole("button", { name: "Tỉnh – giải nhì", exact: true }).click(); await p.waitForTimeout(500); await shot("6_record");
await p.getByRole("button", { name: "Giỏi", exact: true }).first().click(); await next();
await p.locator("select").selectOption("Hà Nội"); await next();
await p.locator('input[aria-label="Tìm ngành hoặc trường"]').fill("y khoa"); await p.waitForTimeout(300); await shot("7_major_search");
await p.locator("ul li button").first().click(); await shot("8_major_chosen"); await next();
await shot("9_priority");
await p.getByRole("button", { name: /Xem kết quả/ }).click(); await p.waitForTimeout(1500); await shot("10_results");
await p.getByText("Vì sao ra kết quả này?").first().click(); await p.waitForTimeout(300); await shot("11_details");
await p.getByText("Không thấy ngành hoặc trường bạn cần?").click(); await p.waitForTimeout(300); await p.screenshot({ path: "out-scenario/t_12_help.png", fullPage: true });
console.log("errors", errs); await b.close();
