/** Vùng miền (bắc, trung, nam) của từng tỉnh/thành phố, dùng để lọc "trong vùng miền em ở". */
export const PROVINCE_REGIONS: Record<string, "bac" | "trung" | "nam"> = {
  "Hà Nội": "bac",
  "TP.HCM": "nam",
  "Hải Phòng": "bac",
  "Đà Nẵng": "trung",
  "Cần Thơ": "nam",
  "Huế": "trung",
  "Đồng Nai": "nam",
  "Bình Dương": "nam",
  "Bà Rịa - Vũng Tàu": "nam",
  "Long An": "nam",
  "Tiền Giang": "nam",
  "An Giang": "nam",
  "Bắc Ninh": "bac",
  "Hưng Yên": "bac",
  "Hải Dương": "bac",
  "Quảng Ninh": "bac",
  "Thái Nguyên": "bac",
  "Nam Định": "bac",
  "Ninh Bình": "bac",
  "Thanh Hóa": "trung",
  "Nghệ An": "trung",
  "Hà Tĩnh": "trung",
  "Quảng Bình": "trung",
  "Quảng Trị": "trung",
  "Quảng Nam": "trung",
  "Quảng Ngãi": "trung",
  "Bình Định": "trung",
  "Khánh Hòa": "trung",
  "Lâm Đồng": "trung",
  "Đắk Lắk": "trung",
  "Gia Lai": "trung",
  "Cà Mau": "nam",
  "Kiên Giang": "nam",
  "Vĩnh Long": "nam",
  "Bến Tre": "nam",
  "Trà Vinh": "nam",
  "Sóc Trăng": "nam",
  "Bạc Liêu": "nam",
  "Tây Ninh": "nam",
  "Bình Phước": "nam",
  "Phú Thọ": "bac",
  "Vĩnh Phúc": "bac",
  "Lào Cai": "bac",
  "Sơn La": "bac",
  "Điện Biên": "bac",
  "Lai Châu": "bac",
  "Hòa Bình": "bac",
  "Hà Nam": "bac",
  "Thái Bình": "bac",
  "Lạng Sơn": "bac",
  "Bắc Giang": "bac",
  "Bắc Kạn": "bac",
  "Cao Bằng": "bac",
  "Hà Giang": "bac",
  "Tuyên Quang": "bac",
  "Yên Bái": "bac",
  "Kon Tum": "trung",
  "Đắk Nông": "trung",
  "Phú Yên": "trung",
  "Ninh Thuận": "trung",
  "Bình Thuận": "trung",
  "Đồng Tháp": "nam",
  "Hậu Giang": "nam",
};
